pipeline {
	agent { label 'docker-agent' }
	tools {
		nodejs 'node24'
	}

	stages {
		stage('Install Dependencies') {
            steps {
                sh "npm install || true"
            }
        }

		stage('Run SonarQube') {
            environment {
                SCANNER_HOME = tool 'sonar-scanner'
            }
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh """
                        ${SCANNER_HOME}/bin/sonar-scanner \
                        -Dsonar.projectKey=simple-express-app-166 \
                        -Dsonar.projectName=simple-express-app-166 \
                        -Dsonar.sources=./simple-express-app/
                    """
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

	}
	post {
		success {
			echo 'Build completed succesfully!'
		}
		failure {
			echo 'Build failed. Check logs.'
		}
	}
}